language: scala
scala: 2.11.5
jdk: oraclejdk8

env:
    - PROJECT=example
    - PROJECT=recfun
    - PROJECT=funsets
    - PROJECT=objset

script:
    - cd $PROJECT && sbt ++$TRAVIS_SCALA_VERSION test
